## Pop quiz

### Q1

In [2]:
def find_heavy_coin(coins):
    # Base case: if there's only one coin, it must be the heavy one
    if len(coins) == 1:
        return coins[0]

    # Split the coins into two equal groups
    midpoint = len(coins) // 2
    group1 = coins[:midpoint]
    group2 = coins[midpoint:]

    # Weigh the two groups
    if sum(group1) > sum(group2):
        # If group1 is heavier, the heavy coin must be in group1
        return find_heavy_coin(group1)
    else:
        # Otherwise, the heavy coin must be in group2
        group2

# List of coin weights: 7 coins with weight 1 and 1 coin with weight 2
coins = [1, 1, 1, 1, 1, 1, 1, 2]

# Find the heavier coin
heavy_coin = find_heavy_coin(coins)
print('The heavy coin is coin number', coins.index(heavy_coin) + 1)

The heavy coin is coin number 8


### Q2

In [3]:
def find_heavy_coin(coins):
    # Base case: if there's only one coin, it must be the heavy one
    if len(coins) == 1:
        return coins[0]

    # Base case: if there are two coins, compare them
    if len(coins) == 2:
        return coins[0] if coins[0] > coins[1] else coins[1]

    # Split the coins into three groups
    third = len(coins) // 3
    group1 = coins[:third]
    group2 = coins[third:2*third]
    group3 = coins[2*third:]

    # Weigh the first two groups
    if sum(group1) > sum(group2):
        # If group1 is heavier, the heavy coin must be in group1
        return find_heavy_coin(group1)
    elif sum(group1) < sum(group2):
        # If group2 is heavier, the heavy coin must be in group2
        return find_heavy_coin(group2)
    else:
        # If they are equal, the heavy coin must be in group3
        return find_heavy_coin(group3)

# List of coin weights: 8 coins with weight 1 and 1 coin with weight 2
coins = [1, 1, 1, 1, 1, 1, 1, 1, 2]

# Find the heavier coin
heavy_coin = find_heavy_coin(coins)
print('The heavy coin is coin number', coins.index(heavy_coin) + 1)

The heavy coin is coin number 9


## Pair programming

In [1]:
import numpy as np

# Global variable for tromino number
tromino_num = 0

def tromino(board, x, y, missing_x, missing_y, size):
    global tromino_num
    
    if size == 2:
        tromino_num += 1
        for i in range(x, x + size):
            for j in range(y, y + size):
                if i != missing_x or j != missing_y:
                    board[i][j] = tromino_num
        return

    tromino_num += 1
    s = size // 2

    # If the missing square is in the top left quadrant
    if missing_x < x + s and missing_y < y + s:
        board[x + s - 1][y + s] = board[x + s][y + s - 1] = board[x + s][y + s] = tromino_num
        tromino(board, x, y, missing_x, missing_y, s) # Recurse on this quadrant
        tromino(board, x, y + s, x + s - 1, y + s, s) # Fill the other quadrants
        tromino(board, x + s, y, x + s, y + s - 1, s)
        tromino(board, x + s, y + s, x + s, y + s, s)
    # If the missing square is in the top right quadrant
    elif missing_x < x + s and missing_y >= y + s:
        board[x + s - 1][y + s - 1] = board[x + s][y + s - 1] = board[x + s][y + s] = tromino_num
        tromino(board, x, y, x + s - 1, y + s - 1, s) # Fill the other quadrants
        tromino(board, x, y + s, missing_x, missing_y, s) # Recurse on this quadrant
        tromino(board, x + s, y, x + s, y + s - 1, s)
        tromino(board, x + s, y + s, x + s, y + s, s)
    # If the missing square is in the bottom left quadrant
    elif missing_x >= x + s and missing_y < y + s:
        board[x + s - 1][y + s - 1] = board[x + s - 1][y + s] = board[x + s][y + s] = tromino_num
        tromino(board, x, y, x + s - 1, y + s - 1, s) # Fill the other quadrants
        tromino(board, x, y + s, x + s - 1, y + s, s)
        tromino(board, x + s, y, missing_x, missing_y, s) # Recurse on this quadrant
        tromino(board, x + s, y + s, x + s, y + s, s)
    # If the missing square is in the bottom right quadrant
    else:
        board[x + s - 1][y + s - 1] = board[x + s - 1][y + s] = board[x + s][y + s - 1] = tromino_num
        tromino(board, x, y, x + s - 1, y + s - 1, s) # Fill the other quadrants
        tromino(board, x, y + s, x + s - 1, y + s, s)
        tromino(board, x + s, y, x + s, y + s - 1, s)
        tromino(board, x + s, y + s, missing_x, missing_y, s) # Recurse on this quadrant

def solve_tromino(size, missing):
    board = np.zeros((size, size))
    missing_x, missing_y = missing
    board[missing_x][missing_y] = -1
    tromino(board, 0, 0, missing_x, missing_y, size)
    return board

print(solve_tromino(8, (0, 1)))

[[ 3. -1.  4.  4.  8.  8.  9.  9.]
 [ 3.  3.  2.  4.  8.  7.  7.  9.]
 [ 5.  2.  2.  6. 10. 10.  7. 11.]
 [ 5.  5.  6.  6.  1. 10. 11. 11.]
 [13. 13. 14.  1.  1. 18. 19. 19.]
 [13. 12. 14. 14. 18. 18. 17. 19.]
 [15. 12. 12. 16. 20. 17. 17. 21.]
 [15. 15. 16. 16. 20. 20. 21. 21.]]
